apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
  namespace: keda
spec:
  channel: stable
  installPlanApproval: Automatic
  name: keda-test
  source: test-catalog
  sourceNamespace: olm
